name: py39text
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - gensim=4.3.3=py39hcfd4151_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - libblas=3.11.0=5_h51639a9_openblas
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=hf598326_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_16
  - libgfortran=15.2.0=h07b0088_16
  - libgfortran5=15.2.0=hdae7583_16
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.51.1=h1b79a29_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - nltk=3.9.1=pyhd8ed1ab_1
  - numpy=1.26.4=py39h7aa2656_0
  - openssl=3.6.0=h5503f6c_0
  - pandas=2.3.1=py39h6aaa60c_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=h7139b31_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h46df422_0
  - regex=2025.7.34=py39he7485ab_0
  - scikit-learn=1.6.1=py39h451895d_0
  - scipy=1.13.1=py39h3d5391c_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smart_open=7.3.0.post1=pyhe01879c_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025c=h8577fbf_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py39he7485ab_0

prefix: "/opt/homebrew/Cellar/micromamba/2.4.0/envs/py39text"
